"""prompt6_dual_committee_roles_and_lane

Revision ID: 109d5510a536
Revises: ad4b61d69412
Create Date: 2026-08-06 22:17:08.577212

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "109d5510a536"
down_revision: str | Sequence[str] | None = "ad4b61d69412"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Revision Prompt 6's 17 new committee roles (8 Investment + 9 Tactical),
# added to the existing `agent_role` enum alongside ADR-038's original 8
# (kept, unremoved, for backward compatibility with already-seeded rows).
_NEW_AGENT_ROLES = [
    "BUSINESS_QUALITY_ANALYST",
    "FUNDAMENTAL_VALUATION_ANALYST",
    "INDUSTRY_COMPETITIVE_ANALYST",
    "LONG_TERM_BULL_ANALYST",
    "LONG_TERM_BEAR_ANALYST",
    "PORTFOLIO_STRATEGIST",
    "INVESTMENT_RISK_MANAGER",
    "INVESTMENT_CIO",
    "MARKET_INTELLIGENCE_ANALYST",
    "TACTICAL_TECHNICAL_ANALYST",
    "EARNINGS_GUIDANCE_ANALYST",
    "NEWS_CATALYST_ANALYST",
    "TACTICAL_BULL",
    "TACTICAL_BEAR",
    "PORTFOLIO_CORRELATION_MANAGER",
    "TRADING_RISK_MANAGER",
    "TRADING_CIO",
]


def upgrade() -> None:
    """Upgrade schema."""
    # Manually added: Alembic's autogenerate does not detect new members
    # added to an existing native Postgres ENUM type (only whole-type
    # create/drop) — same precedent as 6230f16ff209/ad4b61d69412.
    for role in _NEW_AGENT_ROLES:
        op.execute(f"ALTER TYPE agent_role ADD VALUE IF NOT EXISTS '{role}'")
    # ### commands auto generated by Alembic - please adjust! ###
    # `recommendation_mode` already exists (created for `recommendations.mode`)
    # — `create_type=False` so this reuses it rather than trying to
    # recreate it, matching ce0a85382604's precedent for reused enums.
    op.add_column(
        "committee_sessions",
        sa.Column(
            "mode",
            sa.Enum("INVESTMENT", "TACTICAL", name="recommendation_mode", create_type=False),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("committee_sessions", "mode")
    # ### end Alembic commands ###
    # Postgres has no `DROP VALUE` for enum types — the 17 added roles
    # are left in place on downgrade, an accepted, harmless limitation
    # matching every prior `ADD VALUE` migration in this project.
