"""prompt7_order_proposal_and_earnings_risk_policy_fields

Revision ID: 1a65f23b1c9c
Revises: 109d5510a536
Create Date: 2026-08-06 23:28:35.311504

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a65f23b1c9c"
down_revision: str | Sequence[str] | None = "109d5510a536"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `environment_label` already exists (created for
    # `broker_submission_attempts`/`broker_environment_attestations`) —
    # `create_type=False` so this reuses it rather than recreating it,
    # matching ce0a85382604's precedent for reused enums.
    op.add_column(
        "order_proposal_versions",
        sa.Column(
            "environment",
            sa.Enum("RESEARCH", "PAPER", "LIVE", name="environment_label", create_type=False),
            nullable=True,
        ),
    )
    # NOT NULL columns below get an explicit `server_default` — the
    # model's Python-side `default=` only applies to new INSERTs, and
    # this table already has rows from prior revisions' seed data.
    op.add_column(
        "order_proposal_versions",
        sa.Column("outside_hours", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "order_proposal_versions",
        sa.Column(
            "attached_legs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "order_proposal_versions",
        sa.Column("max_slippage_bps", sa.Numeric(precision=8, scale=4), nullable=True),
    )
    op.add_column(
        "order_proposal_versions",
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "order_proposal_versions",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "order_proposal_versions",
        sa.Column("risk_policy_version", sa.String(length=60), nullable=True),
    )
    op.add_column(
        "order_proposal_versions",
        sa.Column("data_cutoff", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "order_proposal_versions",
        sa.Column("quote_observed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "order_proposal_versions",
        sa.Column("requires_approval", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        "risk_policy",
        sa.Column(
            "earnings_risk_budget_pct",
            sa.Numeric(precision=6, scale=4),
            nullable=False,
            server_default="0.0025",
        ),
    )
    op.add_column(
        "risk_policy",
        sa.Column(
            "earnings_risk_budget_max_pct",
            sa.Numeric(precision=6, scale=4),
            nullable=False,
            server_default="0.0050",
        ),
    )
    op.add_column(
        "risk_policy",
        sa.Column(
            "earnings_max_position_pct",
            sa.Numeric(precision=6, scale=4),
            nullable=False,
            server_default="0.1500",
        ),
    )
    op.add_column(
        "risk_policy",
        sa.Column(
            "earnings_max_sector_pct",
            sa.Numeric(precision=6, scale=4),
            nullable=False,
            server_default="0.2500",
        ),
    )
    op.add_column(
        "risk_policy",
        sa.Column(
            "earnings_max_concurrent_trades", sa.Integer(), nullable=False, server_default="3"
        ),
    )
    op.add_column(
        "risk_policy",
        sa.Column(
            "earnings_slippage_bps",
            sa.Numeric(precision=8, scale=4),
            nullable=False,
            server_default="5.0000",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_policy", "earnings_slippage_bps")
    op.drop_column("risk_policy", "earnings_max_concurrent_trades")
    op.drop_column("risk_policy", "earnings_max_sector_pct")
    op.drop_column("risk_policy", "earnings_max_position_pct")
    op.drop_column("risk_policy", "earnings_risk_budget_max_pct")
    op.drop_column("risk_policy", "earnings_risk_budget_pct")
    op.drop_column("order_proposal_versions", "requires_approval")
    op.drop_column("order_proposal_versions", "quote_observed_at")
    op.drop_column("order_proposal_versions", "data_cutoff")
    op.drop_column("order_proposal_versions", "risk_policy_version")
    op.drop_column("order_proposal_versions", "expires_at")
    op.drop_column("order_proposal_versions", "valid_from")
    op.drop_column("order_proposal_versions", "max_slippage_bps")
    op.drop_column("order_proposal_versions", "attached_legs")
    op.drop_column("order_proposal_versions", "outside_hours")
    op.drop_column("order_proposal_versions", "environment")
    # ### end Alembic commands ###
