"""prompt4 point in time evidence layer additions

Revision ID: 6230f16ff209
Revises: ce0a85382604
Create Date: 2026-08-06 14:35:28.140843

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6230f16ff209"
down_revision: str | Sequence[str] | None = "ce0a85382604"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manually added: Alembic's autogenerate does not detect new members
    # added to an existing native Postgres ENUM type (only whole-type
    # create/drop). `ALTER TYPE ... ADD VALUE` is additive and safe to run
    # inside this migration's transaction as long as the new value is
    # never *used* in the same transaction (it isn't — no row insert
    # below references either new value).
    op.execute("ALTER TYPE earnings_timing_category ADD VALUE IF NOT EXISTS 'TIME_NOT_SUPPLIED'")
    op.execute("ALTER TYPE earnings_timing_category ADD VALUE IF NOT EXISTS 'DATE_UNCONFIRMED'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_ingestion_records",
        sa.Column("subject_type", sa.String(length=50), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("provider_record_id", sa.String(length=200), nullable=True),
        sa.Column("revision_id", sa.String(length=100), nullable=True),
        sa.Column("raw_payload_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_provider_ingestion_records_subject",
        "provider_ingestion_records",
        ["subject_type", "subject_id"],
        unique=False,
    )
    op.create_table(
        "earnings_event_corrections",
        sa.Column("earnings_event_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("corrected_field", sa.String(length=40), nullable=False),
        sa.Column("previous_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["earnings_event_id"],
            ["earnings_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_earnings_event_corrections_lookup",
        "earnings_event_corrections",
        ["earnings_event_id", "version_number"],
        unique=False,
    )
    op.add_column(
        "corporate_actions",
        sa.Column(
            "invalidates_earnings_interpretation",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    op.add_column("corporate_actions", sa.Column("note", sa.Text(), nullable=True))
    op.add_column(
        "earnings_consensus_snapshots",
        sa.Column("eps_dispersion", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "earnings_consensus_snapshots",
        sa.Column("usable_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "earnings_guidance_items",
        sa.Column("guidance_midpoint", sa.Numeric(precision=20, scale=4), nullable=True),
    )
    op.add_column(
        "earnings_guidance_items", sa.Column("units", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "earnings_guidance_items", sa.Column("usable_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "earnings_revisions", sa.Column("usable_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "fundamentals_snapshots", sa.Column("usable_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("news_items", sa.Column("usable_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_items", "usable_at")
    op.drop_column("fundamentals_snapshots", "usable_at")
    op.drop_column("earnings_revisions", "usable_at")
    op.drop_column("earnings_guidance_items", "usable_at")
    op.drop_column("earnings_guidance_items", "units")
    op.drop_column("earnings_guidance_items", "guidance_midpoint")
    op.drop_column("earnings_consensus_snapshots", "usable_at")
    op.drop_column("earnings_consensus_snapshots", "eps_dispersion")
    op.drop_column("corporate_actions", "note")
    op.drop_column("corporate_actions", "invalidates_earnings_interpretation")
    op.drop_index("ix_earnings_event_corrections_lookup", table_name="earnings_event_corrections")
    op.drop_table("earnings_event_corrections")
    op.drop_index("ix_provider_ingestion_records_subject", table_name="provider_ingestion_records")
    op.drop_table("provider_ingestion_records")
    # ### end Alembic commands ###
    # Postgres has no `ALTER TYPE ... DROP VALUE` — the two enum values
    # added in upgrade() (TIME_NOT_SUPPLIED, DATE_UNCONFIRMED) are left in
    # place on downgrade. Harmless: no column references them once this
    # revision's own columns are dropped above, and the pre-existing
    # earnings_events.timing_category column (Revision Prompt R3) never
    # writes them itself.
