"""create paper_portfolios, paper_orders, audit_events

Revision ID: 6fa6b9fd2ff4
Revises: bd027d9f35a2
Create Date: 2026-08-03 07:44:35.311746

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fa6b9fd2ff4"
down_revision: str | Sequence[str] | None = "bd027d9f35a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_type", sa.String(length=50), nullable=False),
        sa.Column("ref_id", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_record_type"), "audit_events", ["record_type"], unique=False
    )
    op.create_table(
        "paper_portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starting_cash_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paper_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="paper_order_side"), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "order_type", sa.Enum("MARKET", "LIMIT", name="paper_order_type"), nullable=False
        ),
        sa.Column("limit_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "FILLED",
                "PARTIALLY_FILLED",
                "CANCELED",
                "REJECTED",
                name="paper_order_status",
            ),
            nullable=False,
        ),
        sa.Column("filled_quantity", sa.Integer(), nullable=False),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("filled_avg_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["paper_portfolios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["symbols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paper_orders")
    op.drop_table("paper_portfolios")
    op.drop_index(op.f("ix_audit_events_record_type"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
    # Manually added (same gotcha hit in the Phase 2 migration): op.drop_table()
    # does not drop the native Postgres ENUM types it created.
    sa.Enum(name="paper_order_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="paper_order_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="paper_order_side").drop(op.get_bind(), checkfirst=True)
