"""prompt5 deterministic analytics feature scoring

Revision ID: b5b705be657a
Revises: 6230f16ff209
Create Date: 2026-08-06 21:05:35.079929

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5b705be657a"
down_revision: str | Sequence[str] | None = "6230f16ff209"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_component_results",
        sa.Column("subject_type", sa.String(length=50), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("component_key", sa.String(length=50), nullable=False),
        sa.Column("component_order", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PASS",
                "FAIL",
                "MISSING_DATA",
                "CAPABILITY_UNAVAILABLE",
                name="feature_component_status",
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("calculation_version", sa.String(length=20), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_feature_component_results_subject",
        "feature_component_results",
        ["subject_type", "subject_id"],
        unique=False,
    )
    op.create_table(
        "investment_quality_feature_snapshots",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("evidence_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calculation_version", sa.String(length=20), nullable=False),
        sa.Column("hard_disqualified", sa.Boolean(), nullable=False),
        sa.Column("disqualification_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_investment_quality_feature_snapshots_lookup",
        "investment_quality_feature_snapshots",
        ["instrument_id", "as_of"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_investment_quality_feature_snapshots_lookup",
        table_name="investment_quality_feature_snapshots",
    )
    op.drop_table("investment_quality_feature_snapshots")
    op.drop_index("ix_feature_component_results_subject", table_name="feature_component_results")
    op.drop_table("feature_component_results")
    # ### end Alembic commands ###
    # Manually added (same gotcha hit in every prior migration adding a
    # native Postgres ENUM type): op.drop_table() does not drop the
    # ENUM type itself.
    sa.Enum(name="feature_component_status").drop(op.get_bind(), checkfirst=True)
