"""prompt11_position_monitor_and_post_earnings_confirmation

Revision ID: b66014442014
Revises: c252efe40325
Create Date: 2026-08-09 14:21:37.495153

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b66014442014"
down_revision: str | Sequence[str] | None = "c252efe40325"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Postgres enum values can only be added, never autodetected by
    # autogenerate (only new/changed columns are) — same gotcha as
    # Revision Prompt 9/10's migrations.
    op.execute(
        "ALTER TYPE approval_invalidation_reason ADD VALUE IF NOT EXISTS 'THESIS_INVALIDATED'"
    )

    # `Operations.create_table()` (unlike `op.add_column()`) does not
    # respect an inline `sa.Enum(..., create_type=False)` column's flag
    # — verified directly against this project's pinned alembic/
    # SQLAlchemy versions: it always emits `CREATE TYPE`, which fails
    # for `alert_status` since that type predates this migration (it
    # already backs `alerts.status`). Worked around by creating the
    # table without the two enum columns, then `op.add_column()`-ing
    # them afterward — `add_column()` correctly honors `create_type=False`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_status_events",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_by", sa.String(length=80), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["alerts.id"], name="fk_alert_status_events_alert_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_status_events_alert_id"), "alert_status_events", ["alert_id"], unique=False
    )
    op.add_column(
        "alert_status_events",
        sa.Column(
            "from_status",
            sa.Enum("OPEN", "ACKNOWLEDGED", "DISMISSED", name="alert_status", create_type=False),
            nullable=True,
        ),
    )
    op.add_column(
        "alert_status_events",
        sa.Column(
            "to_status",
            sa.Enum("OPEN", "ACKNOWLEDGED", "DISMISSED", name="alert_status", create_type=False),
            nullable=False,
        ),
    )
    op.create_table(
        "post_earnings_workflow_runs",
        sa.Column("earnings_event_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("pre_event_recommendation_id", sa.Uuid(), nullable=True),
        sa.Column("post_event_recommendation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING_FOR_DATA",
                "CONFIRMED",
                "FAILED",
                "INVALIDATED",
                name="post_earnings_workflow_status",
            ),
            nullable=False,
        ),
        sa.Column("results_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmation_window_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_detected", sa.Boolean(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=150), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name="fk_post_earnings_workflow_runs_account_id"
        ),
        sa.ForeignKeyConstraint(
            ["earnings_event_id"],
            ["earnings_events.id"],
            name="fk_post_earnings_workflow_runs_earnings_event_id",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name="fk_post_earnings_workflow_runs_instrument_id",
        ),
        sa.ForeignKeyConstraint(
            ["post_event_recommendation_id"],
            ["recommendations.id"],
            name="fk_post_earnings_workflow_runs_post_event_recommendation_id",
        ),
        sa.ForeignKeyConstraint(
            ["pre_event_recommendation_id"],
            ["recommendations.id"],
            name="fk_post_earnings_workflow_runs_pre_event_recommendation_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_post_earnings_workflow_runs_earnings_event_id"),
        "post_earnings_workflow_runs",
        ["earnings_event_id"],
        unique=False,
    )
    # `alert_type` is NOT NULL on a table with pre-existing rows (2, from
    # earlier revisions' demo scripts, predating this vocabulary) — a
    # server_default backfills them to SYSTEM_NOTIFICATION (the 19th,
    # catch-all value added specifically for these two out-of-scope,
    # pre-Prompt-11 call sites — see the AlertType docstring) rather than
    # blocking the migration or forcing either into one of the 18 real
    # Prompt 11 types. The default is dropped immediately after so every
    # future insert must name a real type explicitly.
    #
    # `op.add_column()` with an inline `sa.Enum(...)` does NOT auto-create
    # a brand-new Postgres type the way `op.create_table()` does (the
    # same gotcha Revision Prompt 8's migration documents) — the type
    # must be created explicitly first, then every `add_column`
    # referencing it uses `create_type=False`.
    _alert_type_enum = sa.Enum(
        "ENTRY_ZONE_REACHED",
        "APPROVAL_REQUIRED",
        "ORDER_STATUS_CHANGED",
        "TARGET_REACHED",
        "STOP_REACHED",
        "GAP_RISK",
        "THESIS_INVALIDATED",
        "EARNINGS_APPROACHING",
        "RESULTS_AVAILABLE",
        "GUIDANCE_CONFLICT",
        "POST_EARNINGS_CONFIRMATION_READY",
        "POST_EARNINGS_CONFIRMATION_FAILED",
        "TAKE_PARTIAL_PROFIT_SUGGESTION",
        "EXIT_SUGGESTION",
        "DATA_STALE",
        "PROVIDER_OUTAGE",
        "PORTFOLIO_LIMIT_BREACH",
        "MARKET_REGIME_CHANGED",
        "SYSTEM_NOTIFICATION",
        name="alert_type",
    )
    _alert_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "alerts",
        sa.Column(
            "alert_type",
            sa.Enum(
                "ENTRY_ZONE_REACHED",
                "APPROVAL_REQUIRED",
                "ORDER_STATUS_CHANGED",
                "TARGET_REACHED",
                "STOP_REACHED",
                "GAP_RISK",
                "THESIS_INVALIDATED",
                "EARNINGS_APPROACHING",
                "RESULTS_AVAILABLE",
                "GUIDANCE_CONFLICT",
                "POST_EARNINGS_CONFIRMATION_READY",
                "POST_EARNINGS_CONFIRMATION_FAILED",
                "TAKE_PARTIAL_PROFIT_SUGGESTION",
                "EXIT_SUGGESTION",
                "DATA_STALE",
                "PROVIDER_OUTAGE",
                "PORTFOLIO_LIMIT_BREACH",
                "MARKET_REGIME_CHANGED",
                "SYSTEM_NOTIFICATION",
                name="alert_type",
                create_type=False,
            ),
            nullable=False,
            server_default="SYSTEM_NOTIFICATION",
        ),
    )
    op.alter_column("alerts", "alert_type", server_default=None)
    op.add_column("alerts", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("alerts", sa.Column("dedup_key", sa.String(length=200), nullable=True))
    op.add_column("alerts", sa.Column("evidence_type", sa.String(length=50), nullable=True))
    op.add_column("alerts", sa.Column("evidence_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_alerts_unique_open_dedup_key",
        "alerts",
        ["dedup_key"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN' AND dedup_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_alerts_unique_open_dedup_key",
        table_name="alerts",
        postgresql_where=sa.text("status = 'OPEN' AND dedup_key IS NOT NULL"),
    )
    op.drop_column("alerts", "evidence_id")
    op.drop_column("alerts", "evidence_type")
    op.drop_column("alerts", "dedup_key")
    op.drop_column("alerts", "expires_at")
    op.drop_column("alerts", "alert_type")
    op.drop_index(
        op.f("ix_post_earnings_workflow_runs_earnings_event_id"),
        table_name="post_earnings_workflow_runs",
    )
    op.drop_table("post_earnings_workflow_runs")
    op.drop_index(op.f("ix_alert_status_events_alert_id"), table_name="alert_status_events")
    op.drop_table("alert_status_events")
    # ### end Alembic commands ###

    # Manually added (the recurring gotcha this session: op.drop_table()/
    # op.drop_column() does not drop the enum types a column used) —
    # sa.Enum(...).drop() must run after every table/column using it is
    # gone.
    sa.Enum(name="alert_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="post_earnings_workflow_status").drop(op.get_bind(), checkfirst=True)

    # Postgres has no DROP VALUE for an enum type — 'THESIS_INVALIDATED'
    # remains in approval_invalidation_reason's vocabulary after
    # downgrade, the same accepted limitation Revision Prompt 9/10's
    # migrations document.
