"""create symbols, price_bars, indicators

Revision ID: bd027d9f35a2
Revises:
Create Date: 2026-08-03 07:09:48.142616

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd027d9f35a2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "symbols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("asset_type", sa.Enum("EQUITY", "ETF", name="asset_type"), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_symbols_ticker"), "symbols", ["ticker"], unique=True)
    op.create_table(
        "indicators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column(
            "indicator_name",
            sa.Enum(
                "SMA_20",
                "SMA_50",
                "EMA_12",
                "EMA_26",
                "RSI_14",
                "MACD_LINE",
                "MACD_SIGNAL",
                "MACD_HIST",
                "BB_UPPER",
                "BB_MID",
                "BB_LOWER",
                "ATR_14",
                name="indicator_name",
            ),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["symbols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol_id", "as_of", "indicator_name", "version", name="uq_indicator_identity"
        ),
    )
    op.create_table(
        "price_bars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("timeframe", sa.Enum("DAY", name="timeframe"), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("adjustment", sa.String(length=20), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["symbols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_bars_symbol_asof_tf",
        "price_bars",
        ["symbol_id", "as_of", "timeframe"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_bars_symbol_asof_tf", table_name="price_bars")
    op.drop_table("price_bars")
    op.drop_table("indicators")
    op.drop_index(op.f("ix_symbols_ticker"), table_name="symbols")
    op.drop_table("symbols")
    # ### end Alembic commands ###
    # Manually added: op.drop_table() does not drop the native Postgres ENUM
    # types it created, so a downgrade->upgrade round-trip would otherwise
    # fail with "type already exists" on the next upgrade.
    sa.Enum(name="indicator_name").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="timeframe").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="asset_type").drop(op.get_bind(), checkfirst=True)
