"""prompt10_paper_broker_execution

Revision ID: c252efe40325
Revises: 3b795a89a113
Create Date: 2026-08-08 20:27:26.473049

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c252efe40325"
down_revision: str | Sequence[str] | None = "3b795a89a113"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Postgres enum values can only be added, never autodetected by
    # autogenerate (only new/changed columns are) — same gotcha as
    # Revision Prompt 9's MorningPlanSectionKey additions.
    op.execute("ALTER TYPE broker_submission_outcome ADD VALUE IF NOT EXISTS 'TIMEOUT_UNKNOWN'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_auto_policy_versions",
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "eligible_strategy_families",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("min_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_orders_per_day", sa.Integer(), nullable=False),
        sa.Column("max_daily_notional", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("max_per_order_risk_pct", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column(
            "allowed_time_windows",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "allowed_order_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "kill_switch_behavior",
            sa.Enum("HALT_NEW_ONLY", "HALT_AND_CANCEL_OPEN", name="kill_switch_behavior"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["user_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id", "version_number"),
    )
    op.create_index(
        op.f("ix_paper_auto_policy_versions_owner_user_id"),
        "paper_auto_policy_versions",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "cancel_open_orders_events",
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("triggered_by", sa.String(length=80), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("orders_canceled_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "approval_bound_fields",
        sa.Column("quote_price_at_approval", sa.Numeric(precision=18, scale=6), nullable=True),
    )
    op.add_column(
        "broker_submission_attempts", sa.Column("resulting_order_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "broker_submission_attempts",
        sa.Column(
            "request_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "broker_submission_attempts",
        sa.Column(
            "response_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            server_default="{}",
        ),
    )
    op.create_foreign_key(
        "fk_broker_submission_attempts_resulting_order_id",
        "broker_submission_attempts",
        "orders",
        ["resulting_order_id"],
        ["id"],
    )
    op.add_column("order_approvals", sa.Column("auto_policy_version_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_order_approvals_auto_policy_version_id",
        "order_approvals",
        "paper_auto_policy_versions",
        ["auto_policy_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_order_approvals_auto_policy_version_id", "order_approvals", type_="foreignkey"
    )
    op.drop_column("order_approvals", "auto_policy_version_id")
    op.drop_constraint(
        "fk_broker_submission_attempts_resulting_order_id",
        "broker_submission_attempts",
        type_="foreignkey",
    )
    op.drop_column("broker_submission_attempts", "response_snapshot")
    op.drop_column("broker_submission_attempts", "request_snapshot")
    op.drop_column("broker_submission_attempts", "resulting_order_id")
    op.drop_column("approval_bound_fields", "quote_price_at_approval")
    op.drop_table("cancel_open_orders_events")
    op.drop_index(
        op.f("ix_paper_auto_policy_versions_owner_user_id"), table_name="paper_auto_policy_versions"
    )
    op.drop_table("paper_auto_policy_versions")
    # ### end Alembic commands ###

    # Manually added (the recurring gotcha this session: op.drop_table()
    # does not drop the enum types a table's columns used) —
    # sa.Enum(...).drop() must run after the table using it is gone.
    sa.Enum(name="kill_switch_behavior").drop(op.get_bind(), checkfirst=True)

    # Postgres has no DROP VALUE for an enum type — 'TIMEOUT_UNKNOWN'
    # remains in broker_submission_outcome's vocabulary after downgrade,
    # the same accepted limitation Revision Prompt 9's migration documents.
