"""create strategy_versions, recommendations, llm_call_logs

Revision ID: cd811cf4102b
Revises: 6fa6b9fd2ff4
Create Date: 2026-08-03 09:03:27.071640

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd811cf4102b"
down_revision: str | Sequence[str] | None = "6fa6b9fd2ff4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_call_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column(
            "request_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "response_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("strategy_version_id", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("model_response_raw", sa.Text(), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "deterministic_score_inputs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="recommendation_confidence"),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "SUPERSEDED", name="recommendation_status"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["symbols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "paper_orders", sa.Column("linked_recommendation_id", sa.Integer(), nullable=True)
    )
    # Named explicitly (autogenerate emitted None, which downgrade's
    # drop_constraint cannot target reliably).
    op.create_foreign_key(
        "fk_paper_orders_linked_recommendation_id",
        "paper_orders",
        "recommendations",
        ["linked_recommendation_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_paper_orders_linked_recommendation_id", "paper_orders", type_="foreignkey"
    )
    op.drop_column("paper_orders", "linked_recommendation_id")
    op.drop_table("recommendations")
    op.drop_table("strategy_versions")
    op.drop_table("llm_call_logs")
    # ### end Alembic commands ###
    # Manually added (same gotcha hit in Phase 2/3 migrations): op.drop_table()
    # does not drop the native Postgres ENUM types it created.
    sa.Enum(name="recommendation_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="recommendation_confidence").drop(op.get_bind(), checkfirst=True)
