"""r3 decision taxonomy investment thesis earnings evidence morning plan
order authority strategy governance

Revision ID: ce0a85382604
Revises: ece90645a84b
Create Date: 2026-08-05 23:01:00.861980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce0a85382604"
down_revision: str | Sequence[str] | None = "ece90645a84b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_kill_switch_events",
        sa.Column("activated_by", sa.String(length=80), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operating_mode_history",
        sa.Column(
            "mode",
            sa.Enum(
                "RESEARCH_ONLY",
                "PAPER_MANUAL_APPROVAL",
                "PAPER_AUTO_POLICY",
                "LIVE_CONFIRM_EACH_ORDER",
                name="order_authority_mode",
            ),
            nullable=False,
        ),
        sa.Column("changed_by", sa.String(length=80), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decision_policy_versions",
        sa.Column("version_label", sa.String(length=60), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PROPOSED",
                "ACTIVE",
                "REJECTED",
                "SUPERSEDED",
                name="strategy_version_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["user_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_policy_versions_owner_user_id"),
        "decision_policy_versions",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "morning_plan_runs",
        sa.Column("job_run_id", sa.Uuid(), nullable=True),
        sa.Column("plan_date", sa.Date(), nullable=False),
        sa.Column("triggered_by", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "COMPLETED", "FAILED", name="morning_plan_run_status"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_run_id"],
            ["job_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_morning_plan_runs_plan_date"), "morning_plan_runs", ["plan_date"], unique=False
    )
    op.create_table(
        "broker_environment_attestations",
        sa.Column(
            "environment_label",
            sa.Enum("RESEARCH", "PAPER", "LIVE", name="environment_label"),
            nullable=False,
        ),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("broker_endpoint", sa.String(length=200), nullable=False),
        sa.Column("attested_by", sa.String(length=80), nullable=False),
        sa.Column("attested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "morning_plan_versions",
        sa.Column("morning_plan_run_id", sa.Uuid(), nullable=False),
        sa.Column("plan_date", sa.Date(), nullable=False),
        sa.Column(
            "version_label",
            sa.Enum(
                "PRELIMINARY", "FINAL", "AD_HOC", "CORRECTION", name="morning_plan_version_label"
            ),
            nullable=False,
        ),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("evidence_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "completeness_status",
            sa.Enum("COMPLETE", "INCOMPLETE", name="plan_completeness_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["morning_plan_run_id"],
            ["morning_plan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_morning_plan_versions_dashboard",
        "morning_plan_versions",
        ["plan_date", "version_label"],
        unique=False,
    )
    op.create_index(
        op.f("ix_morning_plan_versions_morning_plan_run_id"),
        "morning_plan_versions",
        ["morning_plan_run_id"],
        unique=False,
    )
    op.create_table(
        "risk_policy_versions",
        sa.Column("risk_policy_id", sa.Uuid(), nullable=False),
        sa.Column("risk_budget_pct", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("max_position_pct", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("max_sector_pct", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("max_correlation", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("speculative_position_pct_cap", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["risk_policy_id"],
            ["risk_policy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_risk_policy_versions_lookup",
        "risk_policy_versions",
        ["risk_policy_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "morning_plan_delivery_events",
        sa.Column("morning_plan_version_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.Enum("IN_APP", "COWORK", name="delivery_channel"), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "DELIVERED", "FAILED", name="alert_delivery_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["morning_plan_version_id"],
            ["morning_plan_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_morning_plan_delivery_events_morning_plan_version_id"),
        "morning_plan_delivery_events",
        ["morning_plan_version_id"],
        unique=False,
    )
    op.create_table(
        "morning_plan_input_links",
        sa.Column("morning_plan_version_id", sa.Uuid(), nullable=False),
        sa.Column("input_type", sa.String(length=50), nullable=False),
        sa.Column("input_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["morning_plan_version_id"],
            ["morning_plan_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_morning_plan_input_links_lookup",
        "morning_plan_input_links",
        ["morning_plan_version_id", "input_type"],
        unique=False,
    )
    op.create_table(
        "morning_plan_quality_checks",
        sa.Column("morning_plan_version_id", sa.Uuid(), nullable=False),
        sa.Column("check_name", sa.String(length=60), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["morning_plan_version_id"],
            ["morning_plan_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_morning_plan_quality_checks_morning_plan_version_id"),
        "morning_plan_quality_checks",
        ["morning_plan_version_id"],
        unique=False,
    )
    op.create_table(
        "morning_plan_sections",
        sa.Column("morning_plan_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "section_key",
            sa.Enum(
                "ACT_NOW",
                "APPROVAL_REQUIRED",
                "HOLD_MANAGE",
                "INVESTMENT_WATCH",
                "TACTICAL_WATCH",
                "AVOID",
                "DATA_PROBLEMS",
                name="morning_plan_section_key",
            ),
            nullable=False,
        ),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["morning_plan_version_id"],
            ["morning_plan_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("morning_plan_version_id", "section_key"),
    )
    op.create_index(
        op.f("ix_morning_plan_sections_morning_plan_version_id"),
        "morning_plan_sections",
        ["morning_plan_version_id"],
        unique=False,
    )
    op.create_table(
        "strategy_eligibility_snapshots",
        sa.Column("strategy_version_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_strategy_eligibility_snapshots_lookup",
        "strategy_eligibility_snapshots",
        ["strategy_version_id", "as_of"],
        unique=False,
    )
    op.create_table(
        "earnings_actuals",
        sa.Column("earnings_event_id", sa.Uuid(), nullable=False),
        sa.Column("metric", sa.String(length=30), nullable=False),
        sa.Column("actual_value", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("usable_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["earnings_event_id"],
            ["earnings_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_earnings_actuals_lookup",
        "earnings_actuals",
        ["earnings_event_id", "metric"],
        unique=False,
    )
    op.create_table(
        "earnings_consensus_snapshots",
        sa.Column("earnings_event_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("consensus_eps", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("consensus_revenue", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("num_analysts", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["earnings_event_id"],
            ["earnings_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_earnings_consensus_snapshots_lookup",
        "earnings_consensus_snapshots",
        ["earnings_event_id", "as_of"],
        unique=False,
    )
    op.create_table(
        "earnings_guidance_items",
        sa.Column("earnings_event_id", sa.Uuid(), nullable=False),
        sa.Column("metric", sa.String(length=30), nullable=False),
        sa.Column("guidance_low", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("guidance_high", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("period", sa.String(length=20), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["earnings_event_id"],
            ["earnings_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_earnings_guidance_items_earnings_event_id"),
        "earnings_guidance_items",
        ["earnings_event_id"],
        unique=False,
    )
    op.create_table(
        "earnings_historical_gaps",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("earnings_event_id", sa.Uuid(), nullable=True),
        sa.Column("gap_pct", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["earnings_event_id"],
            ["earnings_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_earnings_historical_gaps_instrument_id"),
        "earnings_historical_gaps",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "event_expected_move_snapshots",
        sa.Column("earnings_event_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("atr_based_move_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("historical_gap_move_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("option_implied_move_pct", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("selected_expected_move_pct", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("calculation_version", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["earnings_event_id"],
            ["earnings_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_event_expected_move_snapshots_lookup",
        "event_expected_move_snapshots",
        ["earnings_event_id", "as_of"],
        unique=False,
    )
    op.create_table(
        "post_earnings_confirmation_snapshots",
        sa.Column("earnings_event_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("results_gate_passed", sa.Boolean(), nullable=False),
        sa.Column("guidance_gate_passed", sa.Boolean(), nullable=False),
        sa.Column("market_reaction_gate_passed", sa.Boolean(), nullable=False),
        sa.Column("all_gates_passed", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["earnings_event_id"],
            ["earnings_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_post_earnings_confirmation_snapshots_lookup",
        "post_earnings_confirmation_snapshots",
        ["earnings_event_id", "as_of"],
        unique=False,
    )
    op.create_table(
        "earnings_feature_snapshots",
        sa.Column("earnings_event_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_pre_event", sa.Boolean(), nullable=False),
        sa.Column("component_price_trend", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("component_analyst_revisions", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("component_options_skew", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("component_peer_reactions", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("component_historical_drift", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("component_guidance_momentum", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("component_technical_setup", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("component_sentiment", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("total_score", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("calculation_version", sa.String(length=20), nullable=False),
        sa.Column("linked_actual_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["earnings_event_id"],
            ["earnings_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["linked_actual_id"],
            ["earnings_actuals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_earnings_feature_snapshots_lookup",
        "earnings_feature_snapshots",
        ["earnings_event_id", "as_of"],
        unique=False,
    )
    op.create_table(
        "investment_theses",
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "UNDER_REVIEW", "INVALIDATED", "CLOSED", name="thesis_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["user_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recommendation_id"),
    )
    op.create_index(
        op.f("ix_investment_theses_instrument_id"),
        "investment_theses",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investment_theses_owner_user_id"),
        "investment_theses",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "investment_thesis_versions",
        sa.Column("investment_thesis_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("valuation_low", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("valuation_mid", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("valuation_high", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("thesis_text", sa.Text(), nullable=False),
        sa.Column("horizon_days_min", sa.Integer(), nullable=True),
        sa.Column("horizon_days_max", sa.Integer(), nullable=True),
        sa.Column("review_date", sa.Date(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investment_thesis_id"],
            ["investment_theses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("investment_thesis_id", "version_number"),
    )
    op.create_index(
        op.f("ix_investment_thesis_versions_investment_thesis_id"),
        "investment_thesis_versions",
        ["investment_thesis_id"],
        unique=False,
    )
    op.create_table(
        "morning_plan_items",
        sa.Column("morning_plan_section_id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_version_id", sa.Uuid(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("headline", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["morning_plan_section_id"],
            ["morning_plan_sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_version_id"],
            ["recommendation_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_morning_plan_items_morning_plan_section_id"),
        "morning_plan_items",
        ["morning_plan_section_id"],
        unique=False,
    )
    op.create_table(
        "order_proposals",
        sa.Column("recommendation_version_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column(
            "mode", sa.Enum("INVESTMENT", "TACTICAL", name="recommendation_mode"), nullable=False
        ),
        sa.Column(
            "side",
            postgresql.ENUM("BUY", "SELL", name="order_side", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "UNDER_EVALUATION",
                "EVALUATED",
                "SUPERSEDED",
                "WITHDRAWN",
                name="order_proposal_status",
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_version_id"],
            ["recommendation_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_order_proposals_account_id"), "order_proposals", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_proposals_recommendation_version_id"),
        "order_proposals",
        ["recommendation_version_id"],
        unique=False,
    )
    op.create_index("ix_order_proposals_status", "order_proposals", ["status"], unique=False)
    op.create_table(
        "recommendation_invalidation_conditions",
        sa.Column("recommendation_version_id", sa.Uuid(), nullable=False),
        sa.Column("condition_text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_version_id"],
            ["recommendation_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendation_invalidation_conditions_recommendation_version_id"),
        "recommendation_invalidation_conditions",
        ["recommendation_version_id"],
        unique=False,
    )
    op.create_table(
        "thesis_review_events",
        sa.Column("investment_thesis_id", sa.Uuid(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investment_thesis_id"],
            ["investment_theses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_thesis_review_events_investment_thesis_id"),
        "thesis_review_events",
        ["investment_thesis_id"],
        unique=False,
    )
    op.create_table(
        "thesis_status_history",
        sa.Column("investment_thesis_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum("ACTIVE", "UNDER_REVIEW", "INVALIDATED", "CLOSED", name="thesis_status"),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum("ACTIVE", "UNDER_REVIEW", "INVALIDATED", "CLOSED", name="thesis_status"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investment_thesis_id"],
            ["investment_theses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_thesis_status_history_investment_thesis_id"),
        "thesis_status_history",
        ["investment_thesis_id"],
        unique=False,
    )
    op.create_table(
        "valuation_snapshots",
        sa.Column("investment_thesis_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("fair_value_low", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("fair_value_mid", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("fair_value_high", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investment_thesis_id"],
            ["investment_theses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_valuation_snapshots_lookup",
        "valuation_snapshots",
        ["investment_thesis_id", "as_of"],
        unique=False,
    )
    op.create_table(
        "order_proposal_versions",
        sa.Column("order_proposal_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "order_type",
            postgresql.ENUM(
                "MARKET", "LIMIT", "STOP", "STOP_LIMIT", name="order_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "time_in_force",
            postgresql.ENUM("DAY", "GTC", name="time_in_force", create_type=False),
            nullable=False,
        ),
        sa.Column("max_notional", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_proposal_id"],
            ["order_proposals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_proposal_id", "version_number"),
    )
    op.create_index(
        op.f("ix_order_proposal_versions_order_proposal_id"),
        "order_proposal_versions",
        ["order_proposal_id"],
        unique=False,
    )
    op.create_table(
        "thesis_catalysts",
        sa.Column("investment_thesis_version_id", sa.Uuid(), nullable=False),
        sa.Column("catalyst_text", sa.Text(), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investment_thesis_version_id"],
            ["investment_thesis_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_thesis_catalysts_investment_thesis_version_id"),
        "thesis_catalysts",
        ["investment_thesis_version_id"],
        unique=False,
    )
    op.create_table(
        "thesis_risks",
        sa.Column("investment_thesis_version_id", sa.Uuid(), nullable=False),
        sa.Column("risk_text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investment_thesis_version_id"],
            ["investment_thesis_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_thesis_risks_investment_thesis_version_id"),
        "thesis_risks",
        ["investment_thesis_version_id"],
        unique=False,
    )
    op.create_table(
        "order_approvals",
        sa.Column("order_proposal_version_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.String(length=80), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                "INVALIDATED",
                name="order_approval_status",
            ),
            nullable=False,
        ),
        sa.Column("integrity_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_proposal_version_id"],
            ["order_proposal_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_approvals_order_proposal_version_id"),
        "order_approvals",
        ["order_proposal_version_id"],
        unique=False,
    )
    op.create_index("ix_order_approvals_status", "order_approvals", ["status"], unique=False)
    op.create_table(
        "order_policy_evaluations",
        sa.Column("order_proposal_version_id", sa.Uuid(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "requested_mode",
            sa.Enum(
                "RESEARCH_ONLY",
                "PAPER_MANUAL_APPROVAL",
                "PAPER_AUTO_POLICY",
                "LIVE_CONFIRM_EACH_ORDER",
                name="order_authority_mode",
            ),
            nullable=False,
        ),
        sa.Column("authorized", sa.Boolean(), nullable=False),
        sa.Column("denial_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_proposal_version_id"],
            ["order_proposal_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_policy_evaluations_order_proposal_version_id"),
        "order_policy_evaluations",
        ["order_proposal_version_id"],
        unique=False,
    )
    op.create_table(
        "approval_bound_fields",
        sa.Column("order_approval_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column(
            "side",
            postgresql.ENUM("BUY", "SELL", name="order_side", create_type=False),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "order_type",
            postgresql.ENUM(
                "MARKET", "LIMIT", "STOP", "STOP_LIMIT", name="order_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("limit_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "time_in_force",
            postgresql.ENUM("DAY", "GTC", name="time_in_force", create_type=False),
            nullable=False,
        ),
        sa.Column("outside_hours", sa.Boolean(), nullable=False),
        sa.Column(
            "attached_legs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("max_notional", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("recommendation_version_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_approval_id"],
            ["order_approvals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_version_id"],
            ["recommendation_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_approval_id"),
    )
    op.create_table(
        "approval_invalidations",
        sa.Column("order_approval_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "PRICE_MOVED",
                "EXPIRED",
                "MANUAL",
                "AMBIGUOUS_IDENTITY",
                "KILL_SWITCH",
                "BOUND_FIELD_CHANGED",
                name="approval_invalidation_reason",
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_approval_id"],
            ["order_approvals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_invalidations_order_approval_id"),
        "approval_invalidations",
        ["order_approval_id"],
        unique=False,
    )
    op.create_table(
        "broker_submission_attempts",
        sa.Column("order_approval_id", sa.Uuid(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "environment_label",
            sa.Enum("RESEARCH", "PAPER", "LIVE", name="environment_label"),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "NOT_ATTEMPTED", "SUCCEEDED", "FAILED", "DENIED", name="broker_submission_outcome"
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_approval_id"],
            ["order_approvals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_broker_submission_attempts_order_approval_id"),
        "broker_submission_attempts",
        ["order_approval_id"],
        unique=False,
    )
    op.create_table(
        "recommendation_attributions",
        sa.Column("recommendation_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "mode", sa.Enum("INVESTMENT", "TACTICAL", name="recommendation_mode"), nullable=False
        ),
        sa.Column("position_lot_id", sa.Uuid(), nullable=True),
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["position_lot_id"],
            ["position_lots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_version_id"],
            ["recommendation_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recommendation_attributions_lot",
        "recommendation_attributions",
        ["position_lot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_attributions_recommendation_version_id"),
        "recommendation_attributions",
        ["recommendation_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_recommendation_attributions_trade",
        "recommendation_attributions",
        ["trade_id"],
        unique=False,
    )
    op.add_column("earnings_events", sa.Column("verified_date", sa.Date(), nullable=True))
    op.add_column("earnings_events", sa.Column("exchange_local_date", sa.Date(), nullable=True))
    # Unlike op.create_table(), op.add_column() on an existing table does not
    # implicitly issue CREATE TYPE for a brand-new sa.Enum column -- it must
    # be created explicitly first (same gotcha as eed7cb451bdc), or the
    # ALTER TABLE fails with "type ... does not exist".
    earnings_timing_category_enum = sa.Enum(
        "BEFORE_OPEN", "AFTER_CLOSE", "DURING_MARKET", "UNKNOWN", name="earnings_timing_category"
    )
    earnings_timing_category_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "earnings_events",
        sa.Column(
            "timing_category",
            earnings_timing_category_enum,
            server_default="UNKNOWN",
            nullable=False,
        ),
    )
    op.add_column(
        "earnings_events", sa.Column("verification_source", sa.String(length=40), nullable=True)
    )
    op.add_column(
        "earnings_events", sa.Column("expected_report_period", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "earnings_events",
        sa.Column(
            "confidence",
            postgresql.ENUM(
                "LOW", "MEDIUM", "HIGH", name="recommendation_confidence", create_type=False
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_earnings_events_report_date", "earnings_events", ["report_date"], unique=False
    )
    op.add_column(
        "earnings_revisions",
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "recommendation_versions", sa.Column("lane_action", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "recommendation_versions", sa.Column("horizon_days_min", sa.Integer(), nullable=True)
    )
    op.add_column(
        "recommendation_versions", sa.Column("horizon_days_max", sa.Integer(), nullable=True)
    )
    op.add_column("recommendation_versions", sa.Column("review_date", sa.Date(), nullable=True))
    recommendation_mode_enum = sa.Enum("INVESTMENT", "TACTICAL", name="recommendation_mode")
    recommendation_mode_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "recommendations",
        sa.Column("mode", recommendation_mode_enum, server_default="TACTICAL", nullable=False),
    )
    op.create_index(
        "ix_recommendations_mode_status", "recommendations", ["mode", "status"], unique=False
    )
    strategy_family_enum = sa.Enum(
        "INVESTMENT_QUALITY",
        "EARNINGS_PRE_EVENT",
        "EARNINGS_POST_CONFIRMATION",
        "GENERIC",
        name="strategy_family",
    )
    strategy_family_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "strategy_definitions",
        sa.Column("family", strategy_family_enum, server_default="GENERIC", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy_definitions", "family")
    op.drop_index("ix_recommendations_mode_status", table_name="recommendations")
    op.drop_column("recommendations", "mode")
    op.drop_column("recommendation_versions", "review_date")
    op.drop_column("recommendation_versions", "horizon_days_max")
    op.drop_column("recommendation_versions", "horizon_days_min")
    op.drop_column("recommendation_versions", "lane_action")
    op.drop_column("earnings_revisions", "ingested_at")
    op.drop_index("ix_earnings_events_report_date", table_name="earnings_events")
    op.drop_column("earnings_events", "confidence")
    op.drop_column("earnings_events", "expected_report_period")
    op.drop_column("earnings_events", "verification_source")
    op.drop_column("earnings_events", "timing_category")
    op.drop_column("earnings_events", "exchange_local_date")
    op.drop_column("earnings_events", "verified_date")
    op.drop_index("ix_recommendation_attributions_trade", table_name="recommendation_attributions")
    op.drop_index(
        op.f("ix_recommendation_attributions_recommendation_version_id"),
        table_name="recommendation_attributions",
    )
    op.drop_index("ix_recommendation_attributions_lot", table_name="recommendation_attributions")
    op.drop_table("recommendation_attributions")
    op.drop_index(
        op.f("ix_broker_submission_attempts_order_approval_id"),
        table_name="broker_submission_attempts",
    )
    op.drop_table("broker_submission_attempts")
    op.drop_index(
        op.f("ix_approval_invalidations_order_approval_id"), table_name="approval_invalidations"
    )
    op.drop_table("approval_invalidations")
    op.drop_table("approval_bound_fields")
    op.drop_index(
        op.f("ix_order_policy_evaluations_order_proposal_version_id"),
        table_name="order_policy_evaluations",
    )
    op.drop_table("order_policy_evaluations")
    op.drop_index("ix_order_approvals_status", table_name="order_approvals")
    op.drop_index(
        op.f("ix_order_approvals_order_proposal_version_id"), table_name="order_approvals"
    )
    op.drop_table("order_approvals")
    op.drop_index(op.f("ix_thesis_risks_investment_thesis_version_id"), table_name="thesis_risks")
    op.drop_table("thesis_risks")
    op.drop_index(
        op.f("ix_thesis_catalysts_investment_thesis_version_id"), table_name="thesis_catalysts"
    )
    op.drop_table("thesis_catalysts")
    op.drop_index(
        op.f("ix_order_proposal_versions_order_proposal_id"), table_name="order_proposal_versions"
    )
    op.drop_table("order_proposal_versions")
    op.drop_index("ix_valuation_snapshots_lookup", table_name="valuation_snapshots")
    op.drop_table("valuation_snapshots")
    op.drop_index(
        op.f("ix_thesis_status_history_investment_thesis_id"), table_name="thesis_status_history"
    )
    op.drop_table("thesis_status_history")
    op.drop_index(
        op.f("ix_thesis_review_events_investment_thesis_id"), table_name="thesis_review_events"
    )
    op.drop_table("thesis_review_events")
    op.drop_index(
        op.f("ix_recommendation_invalidation_conditions_recommendation_version_id"),
        table_name="recommendation_invalidation_conditions",
    )
    op.drop_table("recommendation_invalidation_conditions")
    op.drop_index("ix_order_proposals_status", table_name="order_proposals")
    op.drop_index(
        op.f("ix_order_proposals_recommendation_version_id"), table_name="order_proposals"
    )
    op.drop_index(op.f("ix_order_proposals_account_id"), table_name="order_proposals")
    op.drop_table("order_proposals")
    op.drop_index(
        op.f("ix_morning_plan_items_morning_plan_section_id"), table_name="morning_plan_items"
    )
    op.drop_table("morning_plan_items")
    op.drop_index(
        op.f("ix_investment_thesis_versions_investment_thesis_id"),
        table_name="investment_thesis_versions",
    )
    op.drop_table("investment_thesis_versions")
    op.drop_index(op.f("ix_investment_theses_owner_user_id"), table_name="investment_theses")
    op.drop_index(op.f("ix_investment_theses_instrument_id"), table_name="investment_theses")
    op.drop_table("investment_theses")
    op.drop_index("ix_earnings_feature_snapshots_lookup", table_name="earnings_feature_snapshots")
    op.drop_table("earnings_feature_snapshots")
    op.drop_index(
        "ix_post_earnings_confirmation_snapshots_lookup",
        table_name="post_earnings_confirmation_snapshots",
    )
    op.drop_table("post_earnings_confirmation_snapshots")
    op.drop_index(
        "ix_event_expected_move_snapshots_lookup", table_name="event_expected_move_snapshots"
    )
    op.drop_table("event_expected_move_snapshots")
    op.drop_index(
        op.f("ix_earnings_historical_gaps_instrument_id"), table_name="earnings_historical_gaps"
    )
    op.drop_table("earnings_historical_gaps")
    op.drop_index(
        op.f("ix_earnings_guidance_items_earnings_event_id"), table_name="earnings_guidance_items"
    )
    op.drop_table("earnings_guidance_items")
    op.drop_index(
        "ix_earnings_consensus_snapshots_lookup", table_name="earnings_consensus_snapshots"
    )
    op.drop_table("earnings_consensus_snapshots")
    op.drop_index("ix_earnings_actuals_lookup", table_name="earnings_actuals")
    op.drop_table("earnings_actuals")
    op.drop_index(
        "ix_strategy_eligibility_snapshots_lookup", table_name="strategy_eligibility_snapshots"
    )
    op.drop_table("strategy_eligibility_snapshots")
    op.drop_index(
        op.f("ix_morning_plan_sections_morning_plan_version_id"), table_name="morning_plan_sections"
    )
    op.drop_table("morning_plan_sections")
    op.drop_index(
        op.f("ix_morning_plan_quality_checks_morning_plan_version_id"),
        table_name="morning_plan_quality_checks",
    )
    op.drop_table("morning_plan_quality_checks")
    op.drop_index("ix_morning_plan_input_links_lookup", table_name="morning_plan_input_links")
    op.drop_table("morning_plan_input_links")
    op.drop_index(
        op.f("ix_morning_plan_delivery_events_morning_plan_version_id"),
        table_name="morning_plan_delivery_events",
    )
    op.drop_table("morning_plan_delivery_events")
    op.drop_index("ix_risk_policy_versions_lookup", table_name="risk_policy_versions")
    op.drop_table("risk_policy_versions")
    op.drop_index(
        op.f("ix_morning_plan_versions_morning_plan_run_id"), table_name="morning_plan_versions"
    )
    op.drop_index("ix_morning_plan_versions_dashboard", table_name="morning_plan_versions")
    op.drop_table("morning_plan_versions")
    op.drop_table("broker_environment_attestations")
    op.drop_index(op.f("ix_morning_plan_runs_plan_date"), table_name="morning_plan_runs")
    op.drop_table("morning_plan_runs")
    op.drop_index(
        op.f("ix_decision_policy_versions_owner_user_id"), table_name="decision_policy_versions"
    )
    op.drop_table("decision_policy_versions")
    op.drop_table("operating_mode_history")
    op.drop_table("execution_kill_switch_events")
    # ### end Alembic commands ###
    # Manually added (same gotcha hit in every prior migration that adds a
    # native Postgres ENUM type): op.drop_table()/op.drop_column() does not
    # drop the ENUM type itself. Only types newly created by this revision
    # are dropped here -- types reused from Phase 8 (order_side, order_type,
    # time_in_force, recommendation_confidence, alert_delivery_status,
    # strategy_version_status) are left alone since other tables still
    # reference them after this downgrade.
    sa.Enum(name="strategy_family").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="earnings_timing_category").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="recommendation_mode").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="broker_submission_outcome").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="approval_invalidation_reason").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="order_approval_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="order_proposal_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="thesis_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="morning_plan_section_key").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="delivery_channel").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="morning_plan_version_label").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="environment_label").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="morning_plan_run_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="order_authority_mode").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="plan_completeness_status").drop(op.get_bind(), checkfirst=True)
