"""prompt8_portfolio_lane_attribution_journal_reconciliation

Revision ID: cf5dac1a66e8
Revises: 1a65f23b1c9c
Create Date: 2026-08-08 17:16:13.475271

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf5dac1a66e8"
down_revision: str | Sequence[str] | None = "1a65f23b1c9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_import_batches_account_id"), "import_batches", ["account_id"], unique=False
    )
    op.create_table(
        "reconciliation_runs",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "overall_status",
            sa.Enum("MATCHED", "DISCREPANCY", name="reconciliation_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_runs_account_id"),
        "reconciliation_runs",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "reconciliation_lines",
        sa.Column("reconciliation_run_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("internal_quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("broker_reported_quantity", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column(
            "status",
            sa.Enum("MATCHED", "DISCREPANCY", name="reconciliation_status", create_type=False),
            nullable=False,
        ),
        sa.Column("discrepancy_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"]),
        sa.ForeignKeyConstraint(["reconciliation_run_id"], ["reconciliation_runs.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_lines_reconciliation_run_id"),
        "reconciliation_lines",
        ["reconciliation_run_id"],
        unique=False,
    )
    op.create_table(
        "execution_corrections",
        sa.Column("original_execution_id", sa.Uuid(), nullable=False),
        sa.Column("reversal_execution_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["original_execution_id"], ["executions.id"]),
        sa.ForeignKeyConstraint(["reversal_execution_id"], ["executions.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reversal_execution_id"),
    )
    op.create_index(
        op.f("ix_execution_corrections_original_execution_id"),
        "execution_corrections",
        ["original_execution_id"],
        unique=False,
    )
    op.create_table(
        "import_rows",
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw_line", sa.Text(), nullable=False),
        sa.Column("dedup_key", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IMPORTED", "DUPLICATE_SKIPPED", "ERROR", name="import_row_status"),
            nullable=False,
        ),
        sa.Column("resulting_execution_id", sa.Uuid(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.ForeignKeyConstraint(["import_batch_id"], ["import_batches.id"]),
        sa.ForeignKeyConstraint(["resulting_execution_id"], ["executions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_rows_import_batch_id"), "import_rows", ["import_batch_id"], unique=False
    )
    # Partial unique index — only one row may ever hold the "actually
    # imported" claim per (account_id, dedup_key); multiple
    # DUPLICATE_SKIPPED audit rows for the same key are legitimate.
    op.create_index(
        "ix_import_rows_unique_imported",
        "import_rows",
        ["account_id", "dedup_key"],
        unique=True,
        postgresql_where=sa.text("status = 'IMPORTED'"),
    )
    op.create_table(
        "corporate_action_applications",
        sa.Column("corporate_action_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quantity_before", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("quantity_after", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("cash_credit_amount", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("cash_ledger_entry_id", sa.Uuid(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=140), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.ForeignKeyConstraint(["cash_ledger_entry_id"], ["cash_ledger.id"]),
        sa.ForeignKeyConstraint(["corporate_action_id"], ["corporate_actions.id"]),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_corporate_action_applications_account_id"),
        "corporate_action_applications",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corporate_action_applications_corporate_action_id"),
        "corporate_action_applications",
        ["corporate_action_id"],
        unique=False,
    )
    # `lane` is NOT NULL with a server_default — both `position_lots` and
    # `trades` already have rows from prior revisions' seed data; a lot
    # or trade with no recommendation behind it is `UNCLASSIFIED`, the
    # correct default for pre-existing rows too.
    #
    # `op.add_column()` with an inline `sa.Enum(...)` does NOT auto-create
    # the Postgres type first the way `op.create_table()` does — the type
    # must be created explicitly before the first `add_column` call that
    # uses it (the recurring gotcha this session, this time on the create
    # side rather than the drop side).
    lot_lane_enum = sa.Enum("INVESTMENT", "TACTICAL", "UNCLASSIFIED", name="lot_lane")
    lot_lane_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "position_lots",
        sa.Column(
            "lane",
            sa.Enum("INVESTMENT", "TACTICAL", "UNCLASSIFIED", name="lot_lane", create_type=False),
            nullable=False,
            server_default="UNCLASSIFIED",
        ),
    )
    op.add_column(
        "position_lots", sa.Column("source_recommendation_version_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        "ix_position_lots_lane", "position_lots", ["account_id", "instrument_id", "lane"]
    )
    op.create_foreign_key(
        "fk_position_lots_source_recommendation_version_id",
        "position_lots",
        "recommendation_versions",
        ["source_recommendation_version_id"],
        ["id"],
    )
    op.add_column(
        "trades",
        sa.Column(
            "lane",
            sa.Enum("INVESTMENT", "TACTICAL", "UNCLASSIFIED", name="lot_lane", create_type=False),
            nullable=False,
            server_default="UNCLASSIFIED",
        ),
    )
    op.add_column("trades", sa.Column("linked_order_id", sa.Uuid(), nullable=True))
    op.add_column("trades", sa.Column("modifications_text", sa.Text(), nullable=True))
    op.add_column("trades", sa.Column("mfe", sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column("trades", sa.Column("mae", sa.Numeric(precision=18, scale=6), nullable=True))
    journal_exit_reason_enum = sa.Enum(
        "STOP_HIT",
        "TARGET_HIT",
        "TIME_EXIT",
        "THESIS_BROKEN",
        "TRAILING_STOP",
        "POST_CONFIRMATION_FAILED",
        "MANUAL_EXIT",
        "OTHER",
        name="journal_exit_reason",
    )
    journal_exit_reason_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "trades",
        sa.Column(
            "exit_reason",
            sa.Enum(
                "STOP_HIT",
                "TARGET_HIT",
                "TIME_EXIT",
                "THESIS_BROKEN",
                "TRAILING_STOP",
                "POST_CONFIRMATION_FAILED",
                "MANUAL_EXIT",
                "OTHER",
                name="journal_exit_reason",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column("trades", sa.Column("benchmark_snapshot_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_trades_benchmark_snapshot_id",
        "trades",
        "benchmark_snapshots",
        ["benchmark_snapshot_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_trades_linked_order_id", "trades", "orders", ["linked_order_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_trades_linked_order_id", "trades", type_="foreignkey")
    op.drop_constraint("fk_trades_benchmark_snapshot_id", "trades", type_="foreignkey")
    op.drop_column("trades", "benchmark_snapshot_id")
    op.drop_column("trades", "exit_reason")
    op.drop_column("trades", "mae")
    op.drop_column("trades", "mfe")
    op.drop_column("trades", "modifications_text")
    op.drop_column("trades", "linked_order_id")
    op.drop_column("trades", "lane")
    op.drop_constraint(
        "fk_position_lots_source_recommendation_version_id", "position_lots", type_="foreignkey"
    )
    op.drop_index("ix_position_lots_lane", table_name="position_lots")
    op.drop_column("position_lots", "source_recommendation_version_id")
    op.drop_column("position_lots", "lane")
    op.drop_index(
        op.f("ix_corporate_action_applications_corporate_action_id"),
        table_name="corporate_action_applications",
    )
    op.drop_index(
        op.f("ix_corporate_action_applications_account_id"),
        table_name="corporate_action_applications",
    )
    op.drop_table("corporate_action_applications")
    op.drop_index(op.f("ix_import_rows_import_batch_id"), table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_index(
        op.f("ix_execution_corrections_original_execution_id"),
        table_name="execution_corrections",
    )
    op.drop_table("execution_corrections")
    op.drop_index(
        op.f("ix_reconciliation_lines_reconciliation_run_id"), table_name="reconciliation_lines"
    )
    op.drop_table("reconciliation_lines")
    op.drop_index(op.f("ix_reconciliation_runs_account_id"), table_name="reconciliation_runs")
    op.drop_table("reconciliation_runs")
    op.drop_index(op.f("ix_import_batches_account_id"), table_name="import_batches")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
    # Manually added (the recurring gotcha this session: op.drop_table()/
    # op.drop_column() do not drop the native Postgres ENUM types they
    # created) — drop each new type only after every column/table using
    # it has already been dropped above.
    sa.Enum(name="journal_exit_reason").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="lot_lane").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="import_row_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="reconciliation_status").drop(op.get_bind(), checkfirst=True)
