"""prompt9_morning_plan_dashboard_hierarchy_and_cards

Revision ID: e36f3fdbf6a8
Revises: cf5dac1a66e8
Create Date: 2026-08-08 18:13:32.392620

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e36f3fdbf6a8"
down_revision: str | Sequence[str] | None = "cf5dac1a66e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # New Revision Prompt 9 section keys — autogenerate does not detect
    # new enum *values* on an already-existing Postgres type, only new/
    # changed columns, so these are added by hand (same gotcha as
    # Revision Prompt 4's `earnings_timing_category` additions).
    op.execute("ALTER TYPE morning_plan_section_key ADD VALUE IF NOT EXISTS 'BUY_AND_HOLD'")
    op.execute("ALTER TYPE morning_plan_section_key ADD VALUE IF NOT EXISTS 'TACTICAL_TRADES'")
    op.execute("ALTER TYPE morning_plan_section_key ADD VALUE IF NOT EXISTS 'WATCH_AND_AVOID'")
    op.execute("ALTER TYPE morning_plan_section_key ADD VALUE IF NOT EXISTS 'UPCOMING_EVENTS'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("morning_plan_items", sa.Column("instrument_id", sa.Uuid(), nullable=True))
    op.add_column(
        "morning_plan_items", sa.Column("action_label", sa.String(length=40), nullable=True)
    )
    # NOT NULL with a server_default — `morning_plan_items` already has
    # rows from R3's seed data.
    op.add_column(
        "morning_plan_items",
        sa.Column(
            "card_detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            server_default="{}",
        ),
    )
    op.create_foreign_key(
        "fk_morning_plan_items_instrument_id",
        "morning_plan_items",
        "instruments",
        ["instrument_id"],
        ["id"],
    )
    op.add_column(
        "morning_plan_versions", sa.Column("regime_snapshot_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        "fk_morning_plan_versions_regime_snapshot_id",
        "morning_plan_versions",
        "market_regime_snapshots",
        ["regime_snapshot_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_morning_plan_versions_regime_snapshot_id", "morning_plan_versions", type_="foreignkey"
    )
    op.drop_column("morning_plan_versions", "regime_snapshot_id")
    op.drop_constraint(
        "fk_morning_plan_items_instrument_id", "morning_plan_items", type_="foreignkey"
    )
    op.drop_column("morning_plan_items", "card_detail")
    op.drop_column("morning_plan_items", "action_label")
    op.drop_column("morning_plan_items", "instrument_id")
    # ### end Alembic commands ###
    # Manually added: Postgres has no `ALTER TYPE ... DROP VALUE` — the
    # four new morning_plan_section_key values added in upgrade() are
    # left in place on downgrade (documented, accepted limitation,
    # consistent with this project's existing enum-migration precedent).
